CREATE TABLE USER (
userId BIGINT IDENTITY,
userLogin VARCHAR(255) NOT NULL,
userName VARCHAR(255) NOT NULL,
userAge INT NOT NULL
);

CREATE TABLE MESSAGE (
messageId BIGINT IDENTITY,
messageFromId BIGINT NOT NULL,
messageToId BIGINT NOT NULL,
messageText VARCHAR(255) NOT NULL,
messageDateTime TIMESTAMP
)